spring:
  application:
    name: Scholr
  config:
    import: "optional:file:.env[.properties]"
  rabbitmq:
    addresses: ${MESSAGE_BROKER_URL}
  data:
    redis:
      url: ${REDIS_URL}
  h2:
    console:
      enabled: true
      path: /h2
  datasource:
    url: jdbc:h2:mem:scholrdb;DB_CLOSE_DELAY=-1
    driverClassName: org.h2.Driver
    username: sa
    password: password

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect

resilience4j:
  circuitbreaker:
    instances:
      redisService:
        registerHealthIndicator: true
        slidingWindowSize: 10
        permittedNumberOfCallsInHalfOpenState: 3
        failureRateThreshold: 50
        waitDurationInOpenState: 10s
        slidingWindowType: COUNT_BASED
        recordExceptions:
          - org.springframework.data.redis.RedisConnectionFailureException
          - io.lettuce.core.RedisConnectionException

        cloudinaryService:
          registerHealthIndicator: true
          slidingWindowSize: 5
          failureRateThreshold: 50
          waitDurationInOpenState: 20s
          permittedNumberOfCallsInHalfOpenState: 2


          brokerService:
            registerHealthIndicator: true
            slidingWindowSize: 10
            failureRateThreshold: 50
            waitDurationInOpenState: 15s
            recordExceptions:
              - org.springframework.amqp.AmqpException
              - java.net.ConnectException

          notificationService:
            registerHealthIndicator: true
            slidingWindowSize: 10
            failureRateThreshold: 60
            waitDurationInOpenState: 10s